### ISSUE TITLE
How to generate ODS

### ISSUE THREAD

**Issue by tdsuper** [tmarrinan/omnistereo#1]
Dear @tmarrinan , thanks for sharing the code. 

After compiling main.cpp under the src directory, I tried to run the program. However, because there is no text scene file, i.e. ScanLook_Vehicle07_scene.txt, the program exited. 

Then I compiled main.cpp under demo/src directory and ran the program. The program can successfully render the scene. But the result seems to be not an omnidirectional stereo image.

I also tried to run the program multiple times with different camera_offset. But I don't know whether it is correct to set this parameter.

So could you please give some help? Thanks again!

**Comment by tmarrinan** [comment]
Hmm... I can't replicate the issue you are describing. I did a fresh clone of the repo and built the demo app (requires unzipping the "buildings" model - demo/resrc/models/buildings.zip). Below is the image that I see when running the demo app. Do you see something different?
Note: the demo app isn't rendering both eyes in one frame - you would need to set the offset for the left eye and render, then change the offset for the right eye and render. This can be done via command-line parameter so you don't need to edit code or recompile. Alternatively, the code could be modified to render both (change window size to have 1:1 aspect ratio, and render left eye to viewport of just the top half and right eye to viewport of just the bottom half).

![omnistereo_demo](https://user-images.githubusercontent.com/5696253/133642185-38a62e0c-9374-49d1-8aa4-d2f30cbaa6fa.png)

**Comment by tdsuper** [comment]
Thank you very much for such a quick reply. According to your comment, I think I have run the program correctly. The last question is what is the appropriate value of offset we should set for the left and the right eye when rendering the scene?

**Comment by tmarrinan** [comment]
I believe the unit used in this scene was meters, so +/- 0.0315 would be good for an average person (interpupillary distance of 6.3cm)
